//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace temple
{
    using System;
    using System.Collections.Generic;
    
    public partial class HKeepingStaff
    {
        public int PriestID { get; set; }
        public Nullable<System.DateTime> StaffDate { get; set; }
        public Nullable<int> No_of_Staff { get; set; }
        public Nullable<double> Wage_per_staff { get; set; }
        public Nullable<double> Total_wage { get; set; }
        public int HSid { get; set; }
    
        public virtual Priest Priest { get; set; }
    }
}
